
const Images = {
    DASHW: require('../assets/dashboardWhite.png'),
    DASHB: require('../assets/dashboardBlack.png'),
    ADD: require('../assets/add.png'),
    ADDBLUE: require('../assets/addBlue.png'),
    REGLABW: require('../assets/NuevoLaboratorioW.png'),
    REGLABB: require('../assets/NuevoLaboratorioB.png'),
    USERB: require('../assets/UserB.png'),
    USERW: require('../assets/UserW.png'),
    NEWEXAMPLEB: require('../assets/newExampleB.png'),
    NEWEXAMPLEW: require('../assets/newExampleW.png'),
    SEARCHB: require ('../assets/searchB.png'),
    SEARCHW: require('../assets/searchW.png'),
    SEARCHBLUE: require('../assets/searchBlue.png'),
    CLOSE: require('../assets/close.png'),
    REMOVE: require('../assets/remove.png'),
    DELETE: require('../assets/delete.png'),
    EVALUATIONBLACK: require('../assets/evaluationBlack.png'),
    EVALUATIONWHITE: require('../assets/evaluationWhite.png'),
    NEWLABBLACK: require('../assets/newLabBlack.png'),
    NEWLABWHITE: require('../assets/newLabWhite.png'),

    USEROPTIONIN: require('../assets/userOptionInactive.png'),
    USEROPTIONAC: require('../assets/userOptionActive.png'),
    IMGUSER: require('../assets/imgUser.png'),
    DASH: require('../assets/dashboard.svg'),
    DOWNLOAD: require('../assets/download.png'),
    ARROWDOWN: require('../assets/ArrowDown.png'),
    ARROWUP: require('../assets/ArrowUp.png'),
    ARROWLEFT: require('../assets/arrowLeft.png'),
    ARROWRIGHT: require('../assets/arrowRight.png'),
    CONTRUCTION: require('../assets/contruction.png'),
    FILTERBLUE: require('../assets/filterBlue.png'),
    FILTERWHITE: require('../assets/filterWhite.png')
}
export default Images;
